spring:
  application:
    name: mybootlab
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop # Hibernate database table initialization
#         ddl-auto: none # Spring JDBC database table initialization
  datasource:
    database: h2
    continue-on-error: false
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialize: true
#    schema: classpath:db/schema.sql # Spring JDBC database table initialization
    data: classpath:db/data.sql
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  devtools:
    restart:
      log-condition-evaluation-delta: false
      exclude: static/**,public/**
    org:
      hibernate: DEBUG
  profiles:
    active: dev

my:
  name: default
  secret: ${random.value}
  number: ${random.int}
  bignumber: ${random.long}
  uuid: ${random.uuid}
  number.less.than.ten: ${random.int(10)}
  number.in.range: ${random.int[1024,65536]}

acme:
  enabled: true
  remote-address: "127.0.0.1"
  security:
    username: my
    password: pwd
    roles: [USER, ADMIN]

server:
  port: 8081
  max-http-header-size: 16384
  address: 127.0.0.1
---
spring:
  profiles: dev
my:
  name: dev
---
spring:
  profiles: prod
my:
  name: prod
---
spring:
  profiles: default
my:
  name: default
